### ISSUE TITLE
API 사용 질문있습니다!

### ISSUE THREAD

**Issue by tjrkdgnl** [solvedac/unofficial-documentation#32]
1. 시도했으나 성공하지 못한 문제를 API를 통해 가져올 수 있을까요?

2. 1.이 안된다면 시도했던 문제를 API를 통해 가져올 수 있는지 궁금합니다.

**Comment by RanolP** [comment]
`GET /verify_credentials` 에 관련 정보가 있는 듯 합니다.

**Comment by RanolP** [comment]
30f1efa 에서 보강했습니다
