### ISSUE TITLE
데이터를 추가해 주세요.

### ISSUE THREAD

**Issue by dacoonkr** [solvedac/unofficial-documentation#44]
현재 코인<->조각 환율입니다.
https://solved.ac/api/v3/coins/exchange_rate

현재 상점 판매 목록입니다.
https://solved.ac/api/v3/coins/shop/list

**Comment by RanolP** [comment]
5e1fbe5d87456216cf56cc55206fe945d27b7e6f
2225be9df8c8851d6fefd14dcf42aed9e84fee9c
에서 각각 추가했습니다.
