### ISSUE TITLE
'코인샵 판매 목록 가져오기'에 잘못된 설명이 있습니다.

### ISSUE THREAD

**Issue by 614project** [solvedac/unofficial-documentation#65]
![image](https://github.com/solvedac/unofficial-documentation/assets/71429443/be11e83c-4df5-42a5-9e9d-697be1a6f70f)
별조각이 아니라 코인인거 같습니다.

직접 사용해보니까 유일하게 별조각으로 파는 '저녁 하늘의 별무리' 배경은 10000 으로 뜹니다. 스트릭은 99로 뜨고요.

**Comment by RanolP** [comment]
#67 에서 고쳤습니다.
