### ISSUE TITLE
schemas/SolveTier에서 텍스트가 보이지 않습니다.

### ISSUE THREAD

**Issue by iamgamja** [solvedac/unofficial-documentation#80]
![Screenshot_2024-08-20-23-19-57-320_com kiwibrowser browser-edit](https://github.com/user-attachments/assets/17f39594-7b8c-4041-9a42-61824b40f0ce)

"Master"가 보이지 않습니다. gradient가 글자색이 아닌 배경색에 적용되는 부분이 문제인 것 같습니다.

**Comment by RanolP** [comment]
사용 중인 브라우저가 어떻게 되실까요? text gradient는 전통적으로 background gradient image와 text clip으로 구현되어 왔습니다.
Windows Firefox 및 Windows Chrome에서는 정상적으로 렌더링되는 것을 확인했습니다.

[koosaga 님의 프로필](https://solved.ac/en/profile/koosaga) 등은 해당 브라우저에서 정상적으로 보이시나요?
`background-clip` 속성과 관련된 스타일 이슈일 것으로 추정됩니다.

**Comment by iamgamja** [comment]
[Kiwi Browser](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser&pli=1) 사용 중입니다.

확인해 보니, 브라우저 이슈가 맞는 것 같습니다. `background-clip: text`가 적용이 안되는 이슈가 있네요.
solved.ac에서는 `-webkit-background-clip: text`가 적용되서 잘 보입니다.

![Screenshot_2024-08-21-08-29-32-571_com kiwibrowser browser-edit](https://github.com/user-attachments/assets/f33fce85-fb7c-45ae-ab2a-8c9a711cde8c)

`-webkit-background-clip: text`를 추가해 주실 수 있으신가요?
